### ISSUE TITLE
Create a Navbar 

### ISSUE THREAD

**Issue by phuclinh9802** [phuclinh9802/My_Portfolio_Updated#1]
Navbar should have title, home, what I do, Portfolio, and Contact navigation
<img width="587" alt="Screen Shot 2022-01-27 at 11 37 32 AM" src="https://user-images.githubusercontent.com/44655951/151463872-3f3e34cf-e7a7-4843-9310-325dd25def9c.png">

**Comment by SaintJul** [comment]
Hey!! do you need help with anything else? 😬

**Comment by phuclinh9802** [comment]
Hey, thanks for reaching out. If you could help with general ideas around the color and concept that would be great. I am not really good at designing, and I am using React to recreate my portfolio.

**Comment by SaintJul** [comment]
Yeah sure thing!!!

**Comment by phuclinh9802** [comment]
The design above is what I am following, with the bright color concept.

**Comment by SaintJul** [comment]
Honestly, it's pretty clean already. The only thing I could think of adding is a hover effect. It could underline any accomplishments or texts that you wanted to highlight. I'm leaning towards a red color(rbg 222, 47, 24). I think it's bright enough to get the readers attention while still complimenting your site.

**Comment by phuclinh9802** [comment]
Cool, I will try it. Thank you.

**Comment by SaintJul** [comment]
I'll clone the repo so I can run some more ideas and examples  your way.
